// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnaascftyuruhkbciech.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduYWFzY2Z0eXVydWhrYmNpZWNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzOTIxNTYsImV4cCI6MjA3MDk2ODE1Nn0.aq1ogo5vjqr5ZVWVfZM1cPnNmVBIB0nZ6A-n_hyzEoM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});